### ISSUE TITLE
view 2: risk calculation based on the location

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#11]
For a given place, the user would input the size of an event; she would get a probability estimate someone is infected. 

> Like ... he is organising a concert with 100 ppl - would input 100. Based on the number of active cases and uncertainty, we would calculate the risk (basically just doing the (1-fraction)^N for them)

This will apply to the content reachable via navigation menu "Event Prediction" in the website, after submitting the form on this page.

## Spec
Inputs: 
* size of an event
* date of the event (TBD?)
* (age?)

user clicks on a button

Outputs:
* probability of someone infected being there / getting infected (/ dying?) - ideally as "one out of X people get infected"

## AC
* it's possible to go to this view from the main page, provide the input and get the number based on the estimated risk from the modelled data

**Comment by janpipek** [comment]
Will try to give this a look, together with @Mati-Roy .

**Comment by lagerros** [comment]
The actual calculation listed in here is old, this is the current model we'll be working with: https://www.notion.so/Modelling-d5e0bdaf1733416981ad12c78c69e7d3

**Comment by Bachibouzouk** [comment]
@lagerros and what about view 2? I would guess `request-calculation` (are these view numbers mapped to the actual name of the url path somewhere?) however #52 modifies both `request-calculation` and `selections` (`selections` was also seemingly replaced by `request-event-evaluation`...)

**Comment by lagerros** [comment]
I'm sorry I don't understand the question. The thing that used to be called "view 2" is the same as #52

**Comment by Bachibouzouk** [comment]
Yes but there there is modification of both selections.html template and result-calculations.html template which I believed are two different views. Is view 2 what I get when I click on "Request model" or on "Event prediction", or both?

**Comment by Bachibouzouk** [comment]
@lagerros ? I need to know on which view function I need to implement #52

**Comment by lagerros** [comment]
Sorry for late reply, slack is better for contacting me urgently

**Comment by lagerros** [comment]
View 2 is what you get when you click on "Event prediction", as mvp:ed here http://epidemicforecasting.org/request-event-evaluation

**Comment by Bachibouzouk** [comment]
> View 2 is what you get when you click on "Event prediction", as mvp:ed here http://epidemicforecasting.org/request-event-evaluation

Thanks, I will contact you on slack in the future :)

**Comment by Mati-Roy** [comment]
just FYI / for ref.: I'm starting to work on the UI for the result page now

**Comment by davidoj** [comment]
I submitted this pull request - I can't link it to this issue, perhaps I don't have appropriate permissions
https://github.com/epidemics/covid/pull/96

Details of what was added:
I added the parameter
 - reduction in transmission you expect in your country

It would be good to connect this to the other part of the model - I could replace it with a selection of beta values, for example

I added calculations of:
-  expected direct infections 
- expected second order infections
- excess infections all things considered due to 1 infection at the given stage of the epidemic
- excess hospital burden if the expectation is that the epidemic goes that far

I set the template to display:
 - the probability of 1 attendance
 - the excess infections
 - the excess hospitalisations (if relevant)

Comments:
I had intended to display the expected infections and expected excess infections, but the expected infections number is often low due to the combination of a fairly small transmission probability and usually fairly small infection prevalence (if 10% of the population is infected, you probably know not to host an event). I think this is roughly correct - transmission probabilities are mostly low before peak. I feel a bit like I'm pushing my preferred action over model results, but I'm not super comfortable always showing low results for expected transmissions. One way that early events might hurt is that early transmissions may impact on the dynamics via e.g. reducing the efficacy of contact tracing, but I haven't modelled this.
