### ISSUE TITLE
Add scrolling for containment measures sidebar

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#141]
Currently the sidebar takes over the whole page: 
![image](https://user-images.githubusercontent.com/21347592/76907401-5d9f6680-6863-11ea-8fa0-69d10f85fbcb.png)

We'll want to instead give it a limited height, within which one can scroll down. 

One reason for this is that we might want to fit other things in the sidebar, like additional statistics or an institution logo

**Comment by wolverdude** [comment]
@lagerros It sounds like you want both columns to scroll independently, in which case they would both need to be capped in height.

I'll add a media query so this only applies to large screens since Bootstrap stacks columns for narrow screens, and adding a height restriction in that case could make the site unusable.

**Comment by lagerros** [comment]
I confirm, that sounds good.
