### ISSUE TITLE
New case map view

### ISSUE THREAD

**Issue by jk3141** [epidemics/covid#195]
Risk= active cases / population
Shading in the country's shape with risk, and giving a scale
Probably rescale it so that the place in the world with the highest ratio of infected people to population is dark red, and then down to yellow and green for safer places
The shade is risk. 

(see https://github.com/epidemics/covid/issues/195#issuecomment-602057038)

**Comment by hnykda** [comment]
https://plot.ly/javascript/choropleth-maps/#country-gdp-choropleth-map

**Comment by hnykda** [comment]
Active cases by foretold prediction?

**Comment by hnykda** [comment]
Additional requirements, which can be implemented in other tasks though (depending on if they are easy or not). If it should be in other tasks, please do new cards for it and close this one. From [this](https://epidemicforecasting.slack.com/archives/CV3AQDVMM/p1584721980397700?thread_ts=1584709206.395800&cid=CV3AQDVMM):

* ideally (although very much agree this is not a priority), clicking on a specific circle on the map brings you directly to the related model (currently it by default goes to Hong Kong)
* ideally hoovering over the circle would have a estime number pop up 
* i think the legend should be more salient so that it's right away clear what size and colors represent (i.e. you don't have to look for it in the text)

**Comment by svecon** [comment]
https://google.org/crisisresponse/covid19-map ?

**Comment by jk3141** [comment]
it would be good to switch to
- logarithmic map to the shading (so eg. 0.001-0.01 and 0.01-0.1 are same distance
