### ISSUE TITLE
Move UI code embedded in data files to FE

### ISSUE THREAD

**Issue by wolverdude** [epidemics/covid#276]
Frontend JavaScript logic in the form of Plotly configuration is currently being stored within the uploaded data sets that are being served and used on the frontend. This is extremely brittle and makes customization difficult. Probably not a high priority at the moment, but should be fixed if we get the chance to refactor `lines.js`.

Example [here](https://storage.googleapis.com/static-covid/static/batch-2020-03-26T03-01-41.305671+01-00/lines-traces-albania.json) (snapshot below)

![Screen Shot 2020-03-25 at 9 33 03 PM](https://user-images.githubusercontent.com/4276302/77610565-49e9a500-6ee0-11ea-9576-eb39973523e6.png)

The following should all be in the code on the frontend, not stored in data:

```json
{"hoverlabel": {"namelength": -1}, "line": {"color": "#edcdab", "dash": "solid", "width": 2}, "name": "WEAK seasonality<br>WEAK reduction in air travel"}
```

**Comment by gavento** [comment]
This was intentional and actually made it more robust, but I am open to further improvements! Some notes:

* Naming and color spec in the config files while generating the simulations is more robust and flexible than matching client-side (was brittle before) and is more flexible (adding/changing more scenarios happens in one place and does not need website redeploy, can be shown to people in non-public custom channels).
* This uses Python Plotly API to generate the traces, so is easy and verified by plotly for schema.
* If you want to apply some common style, that is still easy to do (the data is already modified in the JS)
* Technically, no JS logic is there, just data and basic style.

**Comment by gavento** [comment]
(Note: I would agree that having style clearly separated in frontend etc would be "cleaner" and good in a larger project, but I think the gains here are very minor. Feel free to disagree! I would be able to e.g. add some label attributes to the lines (but still would prevent adding without front end commits?))

**Comment by wolverdude** [comment]
The problem is that styling changes have to go out with data changes, and any random frontend dev (like me) is going to be really confused about where these lines are getting styled from. And then the solution they (read: me) are going to come up with is to [overwrite the styles on the frontend](https://github.com/epidemics/covid/blob/daf49fd9b1ec6e5533b72663f0f470df94e13218/src/server/static/js/lines.js#L193-L194), so now it _is_ getting set in two different places.

**Comment by gavento** [comment]
Sorry to hear that and it makes sense; agreed on conceptual level. My intuition would be to not spend more time on it now as it works, including your restyling, but I won't be against any change if you want to go ahead! (I would, however, prefer a solution that would somehow work while e.g. adding or removing new lines out of the box, for example for use in "private" channels.)

**Comment by hnykda** [comment]
We should be able to put the source information used for data-generated stuff in the data so we have the flexibility, right?

**Comment by hnykda** [comment]
@wolverdude I believe it's done as part of the https://github.com/epidemics/epimodel/pull/25 where we don't include stuff like colors etc. anymore (and FE needs to deal with that). So closing.
