### ISSUE TITLE
solve canada moderate vs strong response issue

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#304]
From a user
> While playing around with your public COVID-19 forecasting tool, I observed a strange prediction which I suspect is a bug. In Canada, the prediction for the total number of people infected assuming a moderate response is 150K-3.7M, and the prediction assuming a strong response is 230K-270K. That is, the low-end estimate is higher under a strong response than under a moderate response. Do you know why your model behaves this way?

**Comment by gavento** [comment]
I agree that his may seem confusing, but it is not a bug in data (possibly in presentation).
What the numbers say is that on Moderate the uncertainty (variance) is much higher than on Strong, unsurprisingly, and the mean on Moderate is **way** higher than Strong, as it should be. 

Note that the numbers are results of independent simulations, so such small overlaps are not surprising either.

We are currently fitting normal distributions to estimate the CIs, and perhaps there would be a better distribution or a way to estimate it (but e.g. lognorm does not seem appropriate since there is an upper-bound of ~80% and data concentration around it).

We could have a "cosmetic" solution (e.g. force the lower interval ends monotone, same upper) but it may create other artifacts and would be distorting the statistics (e.g. now they do have a clear simple interpretation independent of other mitigation levels).

**Comment by hnykda** [comment]
Should we close this then?

**Comment by Nora-Ammann** [comment]
Overall, I still think it should be "Explore global **and national** mitigation strength". (I think you can delete the **"the"**.)

And/or, (in the description towards the bottom of the doc), add the specification (**in bold**):

> Mitigation Measures
> 
>  We're modelling **global** mitigation measures via their impact on...

**Comment by hnykda** [comment]
Interpreting "leave" as "leave the site as is"

not

"leave the issue" :grin:
