### ISSUE TITLE
Smaller/no graph legend on mobile

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#314]
60% of our users are on mobile, so it's important we support this use case. 

However, currently the legend hides a lot of the graph: 

![Screenshot_20200330-115101](https://user-images.githubusercontent.com/21347592/77950072-ddbec680-727c-11ea-8433-2c3e51554079.png)

I don't know how to solve this, but we should do _something_ about it.

**Comment by wolverdude** [comment]
@lagerros The chart view is generally terrible on mobile because Plotly's "responsive" implementation is terrible (apparently they've never heard of svg `viewBox` 🤦‍♂). I've figured out a way to maintain a consistent 1:1 size ratio for the chart and solve this problem without eliminating the legend. The downsides are that the text can get awfully small (see image), and I have to modify the HTML elements Plotly creates to do it, which could break unexpectedly if they have unanticipated hooks, but I'll do my best to QA it.

I can't put any more time into this today, so let me know by tomorrow morning if I should proceed in a different direction.

![Screen Shot 2020-03-30 at 3 19 35 PM](https://user-images.githubusercontent.com/4276302/77967610-4ec0a700-729a-11ea-8978-7be9c447c135.png)

**Comment by lagerros** [comment]
Hmm... One thing to watch out for is if something breaks from #315 

Apart from that I don't have the tech chops to decide whether your solution is good or not. Happy to trust your judgement.

**Comment by wolverdude** [comment]
I don't think the technical problems are very likely. I suppose I was more interested in whether you thought the small text was too much of a UI issue.

**Comment by lagerros** [comment]
Aha! Answer is no I don't, seems like the correct trade-off to me.
