### ISSUE TITLE
Add historic FT_Infected to the data

### ISSUE THREAD

**Issue by mathijshenquet** [epidemics/covid#325]
Blocking #251

Currently the `FT_Infected` field is only given for the last day in https://storage.googleapis.com/static-covid/static/data-main-v3.json located in `regions[].data.estimates.days[]`. This is needed for #251.

@gavento could you triage this?

**Comment by hnykda** [comment]
The problem is that we have them only for weeks or something. That means we would have to probably do some interpolation (which would IMO work reasonably well).

But AFAIK @gavento wanted to switch to week granularity anyway  https://epidemicforecasting.slack.com/archives/CV1F9NB5K/p1585942517090100

**Comment by hnykda** [comment]
https://epidemicforecasting.slack.com/archives/C0100EK7N8N/p1586108207100400?thread_ts=1586079875.094500&cid=C0100EK7N8N
