### ISSUE TITLE
Issues with gleamviz data

### ISSUE THREAD

**Issue by mathijshenquet** [epidemics/covid#377]
- [x] ~Population field is missing in `epimodel-data/region.csv` dataset.~ (moved to https://github.com/epidemics/covid/issues/386)
- [ ] Gleamviz trace data is possible incorrect and should be examined for correctness
- [ ] Initial infected is missing in the generated files.

**Comment by gavento** [comment]
1. What is "the gleamviz dataset"? If you mean regions-gleamviz, then yes, part of it is missing (did not have a data source).

2. The trace data in the HDF5 is the _actual fraction_, so "per 1 person"

**Comment by mathijshenquet** [comment]
1. Yeah i mean the hdf5 file
2. I think you divided by 1000 one time to often, or at least thats how it shows up in https://storage.googleapis.com/static-covid/static/data-main-v4.json

**Comment by mathijshenquet** [comment]
See for example: https://storage.googleapis.com/static-covid/static/export-2020-04-11T20-55-11.726933+00-00/extdata-NL.json It is not the case that only 10^-6 people are infected in NL.

**Comment by mathijshenquet** [comment]
So in data v3 it would show infected per 1000 and i claim it currently shows infected per 0.001.

**Comment by gavento** [comment]
Clarification on the data in v4 and gleam HDF:

The data in HDF5 is _daily new_ infected (resp recovered) per 1 person - that is why it is so low compared to prev numbers.
You can compute _cumulative_ infected (resp recovered) by (something like) df.cumsum()

Fro every region separately: Active infected at time t is then cumulative_infected[t]-cumulative_recovered[t]+initial_infected.
The initial_infected is now set to offset the make minimum active value 0 (every epidemic in long sim disappears to near 0)
Note that we will need this heuristic even when we have the initial estimates input to gleam stored (to avoid negatives, since gleam has a bit different region shapes and populations etc.)

**Comment by mathijshenquet** [comment]
Thanks!

**Comment by mathijshenquet** [comment]
As to point 1. I meant the `Population` field in `epimodel-data/region.csv`.

**Comment by mathijshenquet** [comment]
The gleamviz data could still be incorrect. We previously thought it was off by a factor of a 1000 but assuming that it was deltas like Tomas said above needed a multiplication factor of 10k to make sense.

**Comment by hnykda** [comment]
Is this still relevant with https://github.com/epidemics/epimodel/pull/34 merged?

**Comment by hnykda** [comment]
I am going to close this, as I don't think it's needed any more (and we should create more granular issues instead)

**Comment by mathijshenquet** [comment]
No this is basically fixed now
